### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by eeseung** [freemed-it/kit#1]
## 📝 이슈 개요
프로젝트 초기 세팅을 진행합니다. 

## ✅ To-do
- [ ] apps & packages name 변경
- [ ] ui 워크스페이스 세팅
- [ ] husky & lint-staged 설정
